[FIX] account: create taxes at reconciliation
- Create an excluded tax of 20 %
- Create a customer invoice of 1000
- Create a payment of 900
- Make the matching between the invoice and the payment:
  Write-off of 83.33, with the 20 % tax

Error: 'Cannot create unbalanced journal entry'

After commit 89cbef8540ab08af16b7, the tax are by default not created
automatically anymore. We should make sure to pass the context key
`apply_taxes`.

opw-744266

(cherry picked from commit 75c803bbbda447e6357e7a4fefd9e8b39e81f971)