Cherry pick of bc99e456a1a912536ae0554e50e7dd70d34a22b6 failed
stdout:

stderr:

closes odoo/odoo#62568

Error: could not apply bc99e456a1a... [IMP] sale_timesheet: adapt timesheet sections in portal
Hint: after resolving the conflicts, mark the corrected paths
Hint: with 'git add <paths>' or 'git rm <paths>'
Hint: and commit the result with 'git commit'
Related: odoo/enterprise#15040
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>