[FIX] stock_picking_batch: prevent traceback when sorting by zip
Issue Before This Commit:
============================
   A traceback occurs when attempting to sort pickings by zip if any picking has
   a False or empty zip value.

Steps to Produce:
=====================
1. Install the stock_fleet module.
2. Navigate to Batch Transfer in the Stock module under the Operations tab.
3. Create a new batch and add pickings, ensuring some have a zip
   value while others do not.
4. Save the batch, which triggers a traceback error:
   TypeError: '<' not supported between instances of 'bool' and 'str'

With This Commit:
=====================

  The issue occurred because sorting directly on the zip caused an error
  when the zip was False. this fix ensures that sorting treats zip as an empty
  string () when it is False, preventing the error.

task - [4535113](https://www.odoo.com/odoo/my-tasks/4535113)

closes odoo/odoo#196053

X-original-commit: 31999790f8534b2aad6e4617222011b620ac2163
Signed-off-by: Arnold Moyaux (arm) <arm@odoo.com>
Signed-off-by: Dhaval Hadiya (dhha) <dhha@odoo.com>